DROP USER SYSADM CASCADE;

CREATE USER SYSADM IDENTIFIED BY "SYSADM";

GRANT CONNECT, CREATE ANY TABLE, DROP ANY TABLE, CREATE PUBLIC SYNONYM TO SYSADM;

ALTER USER "SYSADM"
DEFAULT TABLESPACE "DATA_ROT"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK;

ALTER USER "SYSADM" QUOTA UNLIMITED ON "DATA_ROT";

QUIT
/
